### ISSUE TITLE
Support HTTP request headers for datapackage exporting

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#112]
@BobHarper1 has wrote:

---

I get an error whenever I try this with a valid url (that works through my browser), even with the example given on [the blog](http://okfnlabs.org/blog/2016/08/01/using-data-packages-with-pandas.html).

`urllib2.HTTPError: HTTP Error 404: Not Found`

Having had a bit of a search, I would need to set the User-Agent header in the HTTP request `urllib2.Request`. Any idea if I could do that in `datapackage.push_datapackage`?

A couple more comments about what's happening (though my ability to test different datapackage urls is limited by not knowing about more).
1. It doesn't seem to be affected by the url scheme, I've tried `http://` or `https://` and both have brought about the same error
2. If I make a basic `urllib2` request on the url as tested with `datapackage.push_datapackage()` I'm able to get the response back no problem

**Comment by roll** [comment]
@BobHarper1
In coming months we will update export/import functionality. Considering to add request headers to export function (`push_datapackage` for now).

**Comment by BobHarper1** [comment]
Thanks!

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/132

Current `push/pull_datapackage` API will not be fixed. There will be an updated API to solve this problem. Merging this issue to general re-implementation tracker.
