### ISSUE TITLE
More detailed error message about invalid json on python2

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/datapackage-py#113]
Hi. Loading invalid json file with datapackage.DataPackage will throw a DataPackageException:

```
>> dp = datapackage.DataPackage('/home/u1/datapackage.json')

  File "/home/u1/.virtualenvs/test-dpm/lib/python2.7/site-packages/datapackage/datapackage.py", line 56, in __init__
    self._descriptor = self._load_descriptor(descriptor)
  File "/home/u1/.virtualenvs/test-dpm/lib/python2.7/site-packages/datapackage/datapackage.py", line 312, in _load_descriptor
    six.raise_from(DataPackageException(msg), e)
  File "/home/u1/.virtualenvs/test-dpm/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
DataPackageException: Unable to load JSON at 'datapackage.json'

```

In the cli tool I would like to display more informative message about parsing error: the line and column where it happened. 

I can extract the original datailed parser error from json parser as `error.__cause__` on python3. But can't do that on python2, because datapackge-py uses `six.raise_from()`, which forgets the original exception on python2.

Yes, one option would be to validate json inside our code before passing it to the datapackage.DataPackage(). But there is a desire to avoid this, and get detailed error message accessible from datapackage-py lib itself.

**Comment by rgrp** [comment]
@roll any updates on this? From my experience, this is the number one issue for users when they get started with a data package and giving them a hint as to **where** there is an issue in the JSON file is essential.

**Comment by roll** [comment]
@rgrp 
I've prioritized it.
