### ISSUE TITLE
datapackage.DataPackage does not allow instance with multiple CSV files in data path

### ISSUE THREAD

**Issue by pcmasuzzo** [frictionlessdata/datapackage-py#119]
Using DataPackage with multiple files (see [here](http://specs.frictionlessdata.io/data-packages/#data-in-files-path)).

`dp = datapackage.DataPackage('datapackage.json')`

where datapackage.json has as resources:

`  "name": "data",
        "path": ["data/data1.csv", "data/data2.csv", "data/data3.csv", "data/data4.csv"]`

Error raised:

`AttributeError: 'list' object has no attribute 'decode'`

which makes me think the problem is in the fact that **path** holds a list of files, instead of a single one.

**Comment by pwalsh** [comment]
@pcmasuzzo this spec change was merged to master prematurely ( cc @rgrp ), in the last week or so, and none of the libraries are updated to reflect the change. Sorry about that. All recent spec changes, which are part of our effort to close down on V1, will be merged into the core libraries in January.

**Comment by pcmasuzzo** [comment]
Many thanks, it'd be great to have it in January!

**Comment by roll** [comment]
Thanks!

I'm merging this issue into general `update specs-v1` issue - https://github.com/frictionlessdata/jsontableschema-py/issues/150
