### ISSUE TITLE
Validate license's names

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#12]
The datapackage schema says:

> The value of the string version SHOULD be an [Open Definition license ID](http://licenses.opendefinition.org/) (preferably one that is Open Definition approved.

So we can't require a certain pattern to the license names, but we could log it, so the user knows.

**Comment by vitorbaptista** [comment]
There's a suggestion on how to validate the names in https://github.com/trickvi/datapackage/issues/43. We could cache that list the same way we cache the registry.

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/131
