### ISSUE TITLE
Be clearer about what .validate() does

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-py#126]
It's not clear enough in the README that the `.validate()` method only validates that the descriptor is well formed according to the specification.  I think "validating a data package" might imply validating that the data is good too.  We should mention what this does and refer to Good Tables for full validation.  Probably also worth mentioning that retrieving the data will result in a `ValueError` if the data doesn't conform to the type specified in the schema.

https://github.com/frictionlessdata/datapackage-py#validating-a-data-package

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/68
