### ISSUE TITLE
Broken dependencies (0.8.9)

### ISSUE THREAD

**Issue by rflprr** [frictionlessdata/datapackage-py#148]
Our package (`datadotworld`), depends on `datapackage-py<1.0a` (pre-v1).
The release `0.8.9` is causing us major issues due to transitive dependency on pre-release versions of other packages.

Specifically, because it depends on `tabulator<1.0.0a`, unless my users install my package using `--pre` nothing works and they are stuck with a `VersionConflict` error.

Please update `datapackage-py` (pre-v1) to eliminate dependencies on pre-release packages, or release `tabulator 1.0.0` as a full release.

Thanks!

**Comment by roll** [comment]
@rflprr 
Could you link (or paste pip error) of this `VersionConflict` error? I'm trying to reproduce it with Python 2 and Python 3:

```
$ pip install datadotworld
``` 

But it works as expected for me.

AFIAK there is no `pip` rule forbidding pre-release dependencies without `--pre` flag.

**Comment by roll** [comment]
@rflprr 
I've localized the problem - pip logic for resolving pre dependency chains we wasn't aware. Working on solution.

**Comment by roll** [comment]
@rflprr 
`tabulator-v1.0.0` has been released.

```bash
$ pip install datadotworld
$ pip list
cchardet (1.1.3)
certifi (2017.4.17)
chardet (3.0.3)
click (6.7)
configparser (3.5.0)
datadotworld (1.2.4)
datapackage (0.8.9)
et-xmlfile (1.0.1)
future (0.16.0)
idna (2.5)
ijson (2.3)
isodate (0.5.4)
jdcal (1.3)
jsonlines (1.1.1)
jsonschema (2.6.0)
jsontableschema (0.10.1)
linear-tsv (1.0.0)
openpyxl (2.4.8)
pip (6.0.8)
python-dateutil (2.6.0)
requests (2.17.3)
rfc3986 (0.4.1)
setuptools (12.0.5)
six (1.10.0)
SQLAlchemy (1.1.10)
tabulator (1.0.0)
unicodecsv (0.14.1)
urllib3 (1.21.1)
xlrd (1.0.0)
```

**Comment by roll** [comment]
FIXED
