### ISSUE TITLE
Matching API version with specs version

### ISSUE THREAD

**Issue by simleo** [frictionlessdata/datapackage-py#149]
Is there a way to find out which version of the specs a given datapackage-py release implements? For instance, if I `pip install datapackage==0.8.9` and use it to validate a data package, which version of the specs am I validating against?

Thanks!

**Comment by roll** [comment]
@simleo 
There is no such API for now. And I suppose we should take a look of providing it.

With `datapackage==0.8.9` is shipped pre-v1 specs - https://pre-v1.frictionlessdata.io/https://pre-v1.frictionlessdata.io/

**Comment by simleo** [comment]
@roll thanks!

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/implementations/issues/19
