### ISSUE TITLE
Update Resource to be compliant to stack reference (use tableschema.Table)

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#15]
# Overview

Stack reference - https://github.com/frictionlessdata/stack
Implementation - https://github.com/frictionlessdata/datapackage-js

# Tasks
- [ ] update Resoure
- [ ] update tests 
- [ ] add csv dialect options tests (#57)

**Comment by vitorbaptista** [comment]
@pwalsh The bullet points about infering a resource's schema on https://github.com/okfn/datapackage-py/issues/1 are crossed out. Does it mean that this isn't needed anymore (at least for now)?

**Comment by pwalsh** [comment]
was crossed out because you created this issue instead :).

**Comment by pwalsh** [comment]
@roll not directly related to v1. We should talk about the relationship between table/schema but after implementing v1 changes.

**Comment by roll** [comment]
FIXED in #139 and #140
