### ISSUE TITLE
Clarify infer behavior in the readme

### ISSUE THREAD

**Issue by wengdanyu** [frictionlessdata/datapackage-py#154]
from datapackage import Package
package = Package('')
package.infer('**/*.csv')
package.descriptor
-----
runing the above code you give,but result is not correct:
package.descriptor shows {'profile':'data-package'} not about the data information relating **.csv

---

# Overview

Functions `infer` and `package.infer` documentation should clarify that it works only with local file system if `glob` is used.

# Plan

- [ ] improve the readme

**Comment by roll** [comment]
@wengdanyu 
Hi! Could you please provide more details. I can't reproduce it:

```python
from datapackage import Package
package = Package()
package.infer('**/*.csv')
print(package.descriptor)
#{'profile': 'tabular-data-package', 'resources': [{'profile': 'tabular-data-resource', 'schema': {'fields': [{'format': 'default', 'type': 'integer', 'name': 'id'}, {'format': 'default', 'type': 'string', 'name': 'city'}], 'missingValues': ['']}, 'path': 'datapackage/data.csv', 'format': 'csv', 'mediatype': 'text/csv', 'encoding': 'utf-8', 'name': 'data'}]}
```

**Comment by wengdanyu** [comment]
I am confused about the infer() method,and the usage of it. If the code above change into 
from datapackage import Package
package = Package()
package.infer('http://health.gov.ie/wp-content/uploads/2017/05/Figure-4.4-Percentage-of-population-covered-by-private-health-insurance-in-Ireland-2011-2013-and-2015.csv
')
why the running result just {'profile': 'data-package'} ??

**Comment by roll** [comment]
@wengdanyu 
The reason of this behavior that `package.infer` works only with local files accepting `glob` pattern as an argument. I'll add a clarification to the readme. Thanks!

To handle remote resources you just need to explicitly add it first:
```python
from datapackage import Package
package = Package()
package.add_resource({'path': 'http://health.gov.ie/wp-content/uploads/2017/05/Figure-4.4-Percentage-of-population-covered-by-private-health-insurance-in-Ireland-2011-2013-and-2015.csv'})
package.infer()
print(package.descriptor)
# {'resources': [{'name': 'Figure-4.4-Percentage-of-population-covered-by-private-health-insurance-in-Ireland-2011-2013-and-2015', 'format': 'csv', 'profile': 'tabular-data-resource', 'schema': {'missingValues': [''], 'fields': [{'name': 'Indicator', 'format': 'default', 'type': 'string'}, {'name': '0 to 17', 'format': 'default', 'type': 'integer'}, {'name': '18 to 29', 'format': 'default', 'type': 'integer'}, {'name': '30 to 39', 'format': 'default', 'type': 'integer'}, {'name': '40 to 49', 'format': 'default', 'type': 'integer'}, {'name': '50 to 59', 'format': 'default', 'type': 'integer'}, {'name': '60 to 69', 'format': 'default', 'type': 'integer'}, {'name': '70 to 79', 'format': 'default', 'type': 'integer'}, {'name': '80 and over', 'format': 'default', 'type': 'integer'}, {'name': 'All ages', 'format': 'default', 'type': 'integer'}]}, 'mediatype': 'text/csv', 'encoding': 'utf-8', 'path': 'http://health.gov.ie/wp-content/uploads/2017/05/Figure-4.4-Percentage-of-population-covered-by-private-health-insurance-in-Ireland-2011-2013-and-2015.csv'}], 'profile': 'tabular-data-package'}
```

**Comment by wengdanyu** [comment]
I have solved this problem by use '=' copy statement 
like that :
ha = package.infer()
print(ha)
so,it can run correctly

**Comment by wengdanyu** [comment]
I have solved this problem by use '=' copy statement
like that :
ha = package.infer(pattern='glob')
print(ha)
so,it can run correctly
