### ISSUE TITLE
UnicodeDecodeError: ‘gbk’ codec can’t decode byte 0x9d in position _init_.py illegal multibyte sequence

### ISSUE THREAD

**Issue by wengdanyu** [frictionlessdata/datapackage-py#157]
cannot read the file

**Comment by wengdanyu** [comment]
it always gets wrong when commit the change of descriptor.

**Comment by pwalsh** [comment]
@wengdanyu can you please let us know which version you are using.

**Comment by wengdanyu** [comment]
@pwalsh python version is 3.6.

**Comment by pwalsh** [comment]
@wengdanyu which version of the datapackage library are you using.

**Comment by wengdanyu** [comment]
@pwalsh    maybe just this sentence :pip install datapackage

**Comment by wengdanyu** [comment]
@pwalsh   pip install datapackage=1.0.0a11 the last version

**Comment by wengdanyu** [comment]
@pwalsh  datapackage is 1.0.0-alpha11

**Comment by roll** [comment]
@wengdanyu 
Please provide a snippet of an actual code you're running and a error traceback. So I'll be able to reproduce the error.

**Comment by roll** [comment]
NOT-CONFIRMED
Please re-open if there will be more information to reproduce the error.
