### ISSUE TITLE
Problem setting resource schema property to use local schema file path

### ISSUE THREAD

**Issue by g8tor** [frictionlessdata/datapackage-py#163]
I am new to using frictionless data's specifications so I could be 
totally off base on this, that said I apologize in advance.

I have multiple files in a directory that share the same schema (but can not
be combined). I would like to use a local file path 
for the schema property as described  (http://specs.frictionlessdata.io/data-resource/)

Esentially, I want to 

- extract the infered schema for the first resource
- write it to disk and set the schema property for all resources to use the local 
schema.json file. See the gist (https://gist.github.com/g8tor/ec3ecc7a9a820ba384cd8b1485cf4083).

I am able to do all of the above, hoever when I try to commit the change on 
the resource by calling resource.commit() I am getting the following:

```
Package Profile: tabular-data-package
Resource Name: tabular-data-resource

Traceback (most recent call last):
  File "demo.py", line 42, in <module>
    resource.commit()
  File "/var/lib/libvirt/images/pyenvs/lib/python3.5/site-packages/datapackage/resource.py", line 265, in commit
    self.__build()
  File "/var/lib/libvirt/images/pyenvs/lib/python3.5/site-packages/datapackage/resource.py", line 286, in __build

    self.__current_descriptor)
  File "/var/lib/libvirt/images/pyenvs/lib/python3.5/site-packages/datapackage/helpers.py", line 165, in expand_resource
_descriptor
    for field in schema.get('fields', []):
AttributeError: 'str' object has no attribute 'get'
```

Checking the expand_resource_descriptor helpers.py file, it looks like its expecting a dict.
which contradicts the spec. Am I correct or am I going about this the wrong way? Any and all help is greatly appreciated.

Thanks In Advance.

Please advise.

Thanks in advance for any and all help.

**Comment by roll** [comment]
@g8tor 
Thanks for the reporting the issue. I'll investigate (probably a bug).

**Comment by g8tor** [comment]
@roll 

No problem at all. .Thanks for your work

**Comment by roll** [comment]
@g8tor 
I would recommend an approach like this:

```python
from datapackage import Package, Resource, infer

SCHEMA_PATH = 'schema.json'

# Infer a schema
resource = Resource('data1.tsv')
resource.infer()
resource.schema.save(SCHEMA_PATH)

# Prepare a descriptor
descriptor = infer('*.tsv')
for resource_descriptor in descriptor['resources']:
  resource_descriptor['schema'] = SCHEMA_PATH

# Create a data package
package = Package(descriptor)
```

This infer/commit system is relatively new so there is a few shortcomings for now. Like in your code `datapackage` wasn't able to dereference the schema (path -> dict). Also `resource.commit` for now will not lead to `package.descriptor` change. We're looking forward to fix all this small issue.

**Comment by g8tor** [comment]
@roll ill give it a try and thanks for the suggestion.

**Comment by roll** [comment]
@g8tor 
You're welcome! Please re-open if needed.
