### ISSUE TITLE
We're using Package.to_json() even though it's deprecated

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#173]
We use `self.to_json()` in `Package.save()` (see https://github.com/frictionlessdata/datapackage-py/blob/3d25cfd2013c0ddb6b5f9ceb7724dcd111fc9905/datapackage/package.py#L216), but this method is deprecated (see https://github.com/frictionlessdata/datapackage-py/blob/3d25cfd2013c0ddb6b5f9ceb7724dcd111fc9905/datapackage/package.py#L429-L438). We should either not deprecate it, or don't use it ourselves.

**Comment by roll** [comment]
@vitorbaptista 
Thanks! Great catch. Will fix.
