### ISSUE TITLE
Allow saving DataPackage with all its resources' data, including remote ones

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#18]
`DataPackage.save()` as implemented https://github.com/okfn/datapackage-py/issues/17 just adds the local resources to the created zip file. It would be useful to have an option to embed all datapackage's data into its zip file as well, so it becomes self-contained.

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/132
