### ISSUE TITLE
Passed in format not used in format recognition

### ISSUE THREAD

**Issue by mcarans** [frictionlessdata/datapackage-py#188]
The format is passed as csv in the below in add_resource but in resource.py line 468 it does this:
```
        inspection['format'] = os.path.splitext(filename)[1][1:]
```
ie. it ignores the passed in format and effectively overwrites it.

eg.
```
from datapackage import Package


package = Package({'title': "UNHCR's populations of concern residing in the British Virgin Islands", 'name': 'refugees-residing-vgb', 'id': '4d801156-3b5c-4867-97b8-da5a584ad0dc', 'description': "Data"})
package.add_resource({'encoding': 'utf-8', 'path': 'http://proxy.hxlstandard.org/data.csv?url=http%3A//popstats.unhcr.org/en/persons_of_concern.hxl&filter01=select&select-query01-01=%23country%2Bresidence=British%20Virgin%20Islands', 'title': 'UNHCR persons of concern residing in the British Virgin Islands.', 'format': 'csv', 'name': 'unhcr_persons_of_concern_residence_vgb.csv'})
package.infer()

```

**Comment by roll** [comment]
Released as `datapackage@1.1.4`

**Comment by mcarans** [comment]
@roll This is fixed, but stepping through the code is confusing as the inferring part is still called but ignored when the format is passed in. IMHO, it would be better to avoid calling the inferring of format altogether for clarity. Perhaps this is something you could look into as you introduce Tabulator's inferring?

**Comment by roll** [comment]
@mcarans 
It's intentionally for now. Concept is that there are two information sources:
- source inspection
- descriptor's metadata
It's independent things and descriptor's metadata have a precedence over source inspection.

**Comment by mcarans** [comment]
@roll If the format is passed in, is there any circumstance in which the source inspection format would be used?

**Comment by roll** [comment]
@mcarans 
No. Output from `_inspect_source` it's kind a fallback metadata but `resource.descriptor` always has precedence.
