### ISSUE TITLE
Support compressed resources

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#191]
# Overview

For now it's on a discussion stage on the specs level - https://github.com/frictionlessdata/specs/issues/290. This issue is for initial thoughts on how it could be done on the implementations level. 

Requires https://github.com/frictionlessdata/tabulator-py/issues/197

**Comment by Mikanebu** [comment]
@roll I am trying to use `tabulator-py` for remote `.zip` format and it throws `Unknown format ‘zip’`. I hope that this feature will solve it. Looking forward to see this feature.

**Comment by roll** [comment]
@Mikanebu 
`tabulator` supports zip from `v1.10` - https://github.com/frictionlessdata/tabulator-py#v110. So if it still doesn't work for `datapackage` it should be something simple like some not passed correct arguments etc. Would you like to take a look and PR?

**Comment by Mikanebu** [comment]
@roll It takes to `stream.py`, line 143, where it looks for `zip` parsers, but there is no parser. Am I in right way? Seems like there is no support for `zip` or `gz`.

**Comment by roll** [comment]
@Mikanebu 
Could you check `tabulator` version used.

**Comment by Mikanebu** [comment]
@roll It is version 1.7.1, I will try with updated version, sorry for taking your time
