### ISSUE TITLE
Error downloading on NLTK packages

### ISSUE THREAD

**Issue by DokMbini** [frictionlessdata/datapackage-py#193]
I get a connection error when downloading all NLTK packages
![image2](https://user-images.githubusercontent.com/28514209/33033823-813aba44-ce2e-11e7-975f-f90285096f1c.jpg)

please  assist

**Comment by roll** [comment]
@DokMbini 
Hi! Could you please provide more context? Not sure it's the right repository for this issue. Is it `datapackage` related erorr?

**Comment by roll** [comment]
@DokMbini 
Closing for now. Please re-open if you're still sure it's a `datapackage-py` error.
