### ISSUE TITLE
Support file objects as a `resource.path`?

### ISSUE THREAD

**Issue by lyschoening** [frictionlessdata/datapackage-py#194]
I would like to generate data packages on the fly in memory while including CSV files in the ZIP file generated by `Package.save()`. Unfortunately, that doesn't seem possible right now because the `Resource` descriptor requires a "path" string. Would it be possible to support providing a file-like object instead of only a "path" here?

**Comment by roll** [comment]
@lyschoening 
It's something to think about because it will be a non-standard extension for the specs on the implementation level.

**Comment by vincentchevrier** [comment]
Also looking for this functionality.

**Comment by roll** [comment]
In [Frictionless Framework](https://github.com/frictionlessdata/tableschema-py#tableschema-py) it's possible to provide any data source acceptable by `Table` to `resource.data`. Please try it :+1:
