### ISSUE TITLE
Use datapackage's base path when loading custom profiles 

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#195]
For example, consider the datapackage:

```json
{
    "name": "test",
    "title": "Test",
    "profile": "my-data-profile.json"
}
```

The `my-data-profile.json` should be loaded relative to the `datapackage.json` path, otherwise we would need to use the absolute path, which isn't portable.

**Comment by roll** [comment]
If it doesn't use the data package directory for now - it's a bug.
