### ISSUE TITLE
Is it possible to reference a schema defined in the datapackage itself?

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#198]
For example, https://github.com/cmoa/collection/blob/3603ad5f5ed121f0ff5fc76b2e0ffb5f63974db1/datapackage.json#L33.

They use a format similar to:

```javascript
{
  "resources": [
    {
      "schema": "my-schema",
      // ...
    },
  ],
  "schemas": {
    "my-schema": {
      // The schema itself
    }
  }
}
```

I haven't seen this pattern in the [Tabular Data Resource](https://frictionlessdata.io/specs/tabular-data-resource/) specification, but I'm not sure if it used to be supported.

**Comment by roll** [comment]
Technically - yes - https://github.com/frictionlessdata/datapackage-py/blob/master/tests/test_package.py#L136. It's possible using JSON Pointers.

But it has been removed from the specs.
