### ISSUE TITLE
documentation regarding "last_updated" in datapackage.json

### ISSUE THREAD

**Issue by nabinkhadka** [frictionlessdata/datapackage-py#202]
I have seen "last_updated" being used in number of places, like https://github.com/datasets/gdp/blob/master/datapackage.json
But I cannot find anywhere in documentation https://frictionlessdata.io/specs/data-package/

Can you please help?

**Comment by roll** [comment]
@nabinkhadka 
The data package specification allows using any user-defined properties like `last_updated` or others. So it's a custom property used for this concrete data package e.g. `gdp`.

Please re-open if you have some other questions :+1:
