### ISSUE TITLE
save method does not respect base_path

### ISSUE THREAD

**Issue by dahlbaek** [frictionlessdata/datapackage-py#205]
For instances of the Package and Resource classes, the save method does not take into account the `base_path` argument of the instance when saving to json. From the [documentation](https://github.com/frictionlessdata/datapackage-py#packagedescriptor-base_pathnone-strictfalse-storagenone-options), I would expect the `target` argument to contain a relative path (tested with the `helpers.is_safe_path` function), to be appended to `base_path`.

If you would like, I could try my hand at a PR.

**Comment by roll** [comment]
Switching to a feature label.

Proposed design:
```
package.save('path.json', to_base_path=True)
```
