### ISSUE TITLE
Dynamic resources? 

### ISSUE THREAD

**Issue by cottrell** [frictionlessdata/datapackage-py#207]
Not sure if there is a discussion board. Is there a view on patterns for dynamic datasets or rather dynamic resources? For example hourly files or growing lists of user records.

**Comment by roll** [comment]
Hi @cottrell, probably the best place for this discussion is the specs issue tracker - https://github.com/frictionlessdata/specs/issues (cc @rufuspollock)

**Comment by cottrell** [comment]
https://github.com/frictionlessdata/specs/issues/590
