### ISSUE TITLE
Resource raw_read() method cannot read the GeoJSON data

### ISSUE THREAD

**Issue by wengdanyu** [frictionlessdata/datapackage-py#215]
datapackage        1.1.4
python 3.6
the case from this website:[https://frictionlessdata.io/docs/joining-data-in-python/]
>>> world = json.loads(countries_dp.get_resource('countries') .raw_read()**.decode(
'UTF-8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\datapackage\resource.py", line 218, in raw_read
    for chunk in self.iter():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\datapackage\resource.py", line 166, in iter
    raise exceptions.DataPackageException(message)
tableschema.exceptions.DataPackageException: **Methods iter/read are not supported
 for non tabular data**

**Comment by roll** [comment]
@wengdanyu 
Please upgrade the lib version to 1.2.4+. It was fixed - https://github.com/frictionlessdata/datapackage-py/commits/master

**Comment by wengdanyu** [comment]
@roll  get it!
