### ISSUE TITLE
Move package.base_path to the main API

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/datapackage-py#216]
Hi
Hoping to use package's `base_path` property to make it easier to find, say, a README.md in uploaded datapackage in [datapackager.](https://github.com/frictionlessdata/ckanext-datapackager/issues/60).
I note though that the property mentions its use is [deprecated](https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/package.py#L408)?
Any chance this warning was meant just for [default_base_path](https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/package.py#L57-L58)?
Just want to make sure I'm using the right reference. Thanks in advance.

**Comment by roll** [comment]
@mattRedBox 
It was deprecated as a part of API simplification.

Because there is a clear use case (https://github.com/frictionlessdata/ckanext-datapackager/issues/60) let's move it to the main API. 

Anyway you can safely use it while it exists in actual API and we have this issue

**Comment by roll** [comment]
Fixed by #217 

---

Release is blocked by https://github.com/frictionlessdata/specs/issues/616
