### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by uvchik** [frictionlessdata/datapackage-py#221]
We use `datapackage` in our project and tests on travis-ci with python 3.7 fail, due to a problem with the cChardet package. In your requirements cchardet is restricted to <2.0.

1. Is there a reason why the most actual version of cchardet is not used? I do not know if it actually solves the problem, but it cannot be solved with this restriction in the future.

2. Are you planing to support Python 3.7 in the future?

**Comment by roll** [comment]
Hi @uvchik,
There was already an effort to increase `cchardet` version - https://github.com/frictionlessdata/datapackage-py/pull/219/files (but we need need `<=3` I think). But tests fail.

I suppose there are minor breaking changes in `cchardet` (the reason we have it as `<=2`). @akariv WDYT - is it OK to bump(will it be non-breaking actually)?

**Comment by thenouch** [comment]
Hi there, I stumbled upon this after having the same issues in regards to installing the package. If there's any work arounds, I'd appreciate the support. Version of Python that I'm currently using is 3.72

**Comment by roll** [comment]
Would someone like to have a go on this issue? 

We need to add `python3.7` to the `.travis.yml` and make a PR pass the test. It could be easy (to not). But it makes sense to try anyway. Unfortunately, I can't do it by myself upcoming weeks.

**Comment by billwanjohi** [comment]
I successfully installed the `cchardet>=2.1.3` wheel on Python 3.7. Based on the tags attached to [the commit](https://github.com/PyYoshi/cChardet/commit/3329969fcc1d086be729d59d32eed475e097225c), it doesn't look like they're planning on backporting support to the 1.x series.

**Comment by OriHoch** [comment]
fixed in #227

**Comment by roll** [comment]
Thanks!

**Comment by roll** [comment]
v1.5+

**Comment by uvchik** [comment]
Great. Thanks :clap:

**Comment by thenouch** [comment]
Awesome, thank you very much. Works like a charm now.
