### ISSUE TITLE
Conda dependencies that require cchardet<2.0 out of sync w/ setup.py

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/datapackage-py#237]
Despite the fact that the `datapackage-py` `setup.py` script in the GitHub repository requires only `cchardet>=1.0`, the distributed package in the `conda-forge` channel for v1.6.0 still impose a maximum `cchardet` version of `<2.0`. (see `conda` output below). This means that `datapackage-py` can't be used in a software environment alongside Python 3.7.

```
(pudl) %0 ~/code/catalyst/pudl% conda search datapackage=1.6.0 --info
Loading channels: done
datapackage 1.6.0 py_0
----------------------
file name   : datapackage-1.6.0-py_0.tar.bz2
name        : datapackage
version     : 1.6.0
build       : py_0
build number: 0
size        : 40 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/datapackage-1.6.0-py_0.tar.bz2
md5         : 301bccf1d84bac7e45aec0d500f400cc
timestamp   : 2019-04-11 14:33:33 UTC
dependencies: 
  - cchardet >=1.0,<2.0
  - click >=6.7,<7.0
  - jsonpointer >=1.10,<2.0
  - jsonschema >=2.5,<3.0
  - python
  - requests >=2.8,<3.0
  - six >=1.10,<2.0
  - tableschema >=1.1.0,<2.0
  - tabulator >=1.3,<2.0
  - unicodecsv >=0.14,<2.0

**Comment by zaneselvans** [comment]
This definitely seems weird, given that [the setup.py version tagged for 1.6.0](https://github.com/frictionlessdata/datapackage-py/blob/aca085ea54541b087140b58a81332f8728baeeb2/setup.py) definitely doesn't have these requirements.

**Comment by roll** [comment]
@zaneselvans 
It's really weird because `datapackage` has had this `<2` requirements lately - https://github.com/frictionlessdata/datapackage-py/commit/411675ddfc15ee9358a4aad5a287dad219731afd (it was `<3` so not sure from where this `<2` is coming)

Is it possible that some underlying dependencies is not updated?

**Comment by roll** [comment]
I see it's coming from `tabulator@1.3` which is a dependency from `datapackage`. I'm releasing `datapackage@1.6.2` with updated tabulator dependency.

**Comment by zaneselvans** [comment]
Yay! Great. Glad it's figured out.
