### ISSUE TITLE
add howto for proxy server to documentation

### ISSUE THREAD

**Issue by renxida** [frictionlessdata/datapackage-py#238]
It took me a little to figure out, but in order to fetch data with a proxy server, one has to do the following before running Package("https://xxx.json"):

import os 
os.environ["HTTP_PROXY"] = 'xxx' 
os.environ["HTTPS_PROXY"] = 'xxx'

I wonder if we could add this to the documentation? I searched for "proxy" on the repo with 0 results. I also checked the tableschema repo to no avail.

**Comment by roll** [comment]
Thanks! 

It's added
