### ISSUE TITLE
How to add_resource() without modifying the resource descriptor?

### ISSUE THREAD

**Issue by andrejjh** [frictionlessdata/datapackage-py#240]
Working on  [FrictionlessDarwinCore](https://github.com/frictionlessdata/FrictionlessDarwinCore), I've created classes that derive from datapackage classes.
I'm trying to create resource&package descriptors where Darwin Core fields type, format and constraints are deduced from the field name (see this [table](https://github.com/frictionlessdata/FrictionlessDarwinCore/blob/master/data/fdwc_terms.csv)). Eg eventDate should receive a 'string' type and 'default' format.
It works fine at resource level (see my test_package.py) but not at package level.
It seems that package.add_resource() invokes _build() that does not take into account my descriptor and rather infer fields type and format from the file content. eg eventDate receives 'date' type which is not what I want because this field, according to the DarwinCore standards, might contain a date, a datetime but also a range of dates or datetime.

Is there a way for me to 'force' my DwCResource descriptor to have precedence over the standard datapackage.Resource inferred descriptor?

**Comment by roll** [comment]
@andrejjh 
Is it possible in your code to:
- `infer` all the metadata first
- patch it with metadata that has precedence

**Comment by andrejjh** [comment]
This is technically feasible but not ideal as almost all DwC fields will have to be patched after the infer(). I would rather build the DataPackage descriptor from scratch with type, format and constraints derived from Dwc terms. Assembling this into resources and package descriptor is not a big deal.
