### ISSUE TITLE
Release v1.8.0 on conda-forge

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/datapackage-py#245]
PyPI now has version `datapackage-py` v1.8.0 available, but this version doesn't appear to have been pushed to `conda-forge`.  Maybe there's a way to automate the conda packaging whenever a new version is released?

**Comment by roll** [comment]
Hi @zaneselvans, no their system is fully manual. Now I'm waiting for this PR to be merged - https://github.com/conda-forge/tabulator-feedstock/pull/18 (I'm not a contributor there) - to merge analogous for `datapackage@1.8` (I'm a contributor for).

**Comment by roll** [comment]
Released - https://anaconda.org/conda-forge/datapackage
