### ISSUE TITLE
Question: Single Data Package definition for multiple data validations

### ISSUE THREAD

**Issue by hjoukl** [frictionlessdata/datapackage-py#248]
# Overview

Question: How to use a single/canonical Data Package (and Table Schema) definition for data validation of different data payloads?
 
## Note
Please excuse my (ab)using the tracker for a question - I probably haven't found the proper channel to discuss such issues(?).

Table Schema + Data Package are really impressive - I wonder why I stumbled upon them just now. Nice work!

# Details
The datapackage spec defines the required JSON Resource.path as either a URL or a local relative path (sub-path actually, i.e. mustn't start with ".."). 

Therefore, any actual data files must be located in the same base path as the datapackage & schema definitions.

The datapackage-py Resource object implementation joins its base_path `__init__` argument and Resource.path into the read-only "source" property. base_path used both as the base path for datapackaga (schema) resources and also for the actual data files.

In combination, this makes it pretty difficult to allow for validating
- separate sets of data files with changing paths or names, e.g. timestamps like customer_20190331.csv:
  - you can't use customizable file prefixes/suffixes for such filenames
  - you can't change the private self.__source_inspection attribute unless resolving to hacks
- data files residing in locations separate from the datapackage definition (I realize this is meant as a security feature and could be worked around by serving the files through a simple http server; still, it's rather inconvenient)

So I'm wondering: Am I missing something? Is this kind of validation use case not something that datapackage targets?

Ideas that come to mind:
- Rather use separate `package_path` and `data_path` parameters (although strictly speaking such an implementation would violate the spec when prefixing data files with a different base path)?
- Add some "generic" support for paths/file names (like "{data_path}/{file_prefix}my-data-file{file-suffix}.csv" in implementation and/or spec?
- As a user, bite the bullet and always preprocess each data-under-validation before validation, i.e. change all filenames to canonical names, copy the files into the datapackage definition files tree, ...)

---

Please preserve this line to notify @roll (maintainer of this repository)

**Comment by roll** [comment]
Hi @hjoukl,

Thanks for the question and ideas! 

The library is meant to be an implementation of https://frictionlessdata.io/specs/ so the path is static on purpose to follow the `data-package/resource` spec.

Have you tried https://github.com/frictionlessdata/goodtables-py? This tool is more focused on validation so you can do something like this:

```python
from goodtables import validate

for path in your_data_paths:
    report = validate(path, schema='your_common_schema_path')
```

**Comment by hjoukl** [comment]
Thanks for following up!
Yes, I realize this is tooling that implements the spec - that's what makes it so attraktive 🙂. Especially the mechanisms of packaging interdependent tables with foreign key relations.
Have to look up on goodtables. At first glance though there doesn't seem to be foreign key support (yet), and handling of a package of multiple csv files is a bit unclear from the docs.
Of course, I could always generate a datapackage json on the fly to support my needs. 
Again, thanks - great tool, and moreover superb Specs.

**Comment by roll** [comment]
Hopefully, I will release FK support for `goodtables` soon - https://github.com/frictionlessdata/goodtables-py/pull/306

Thanks!
