### ISSUE TITLE
Connecting to datapackage docs via intersphinx

### ISSUE THREAD

**Issue by danielhuppmann** [frictionlessdata/datapackage-py#258]
# Overview

Is there a url to connect to the datapackage-API docs using intersphinx when building the docs for a package that can read/write `datapackage.Package`? None of the documentations on frictionless.io, pypi, conda-forge or this repo seem to have this...

i.e., a resource that can be used in this way.
```
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
}
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @danielhuppmann,

I'm not sure it's possible due to we don't use Sphinx formatted docstrings.

For now, the entry points for the docs is https://github.com/frictionlessdata/datapackage-py#datapackage-py but we're working on a dedicated docs protal atm

**Comment by danielhuppmann** [comment]
Thanks! I added the link as a link in [our docs](https://pyam-iamc.readthedocs.io/en/latest/api/io.html#the-frictionless-data-package) for now - but it would be great to have the reference build automatically with intersphinx in the future.

**Comment by roll** [comment]
Thanks!

cc @lwinfree https://pyam-iamc.readthedocs.io/en/latest/index.html
