### ISSUE TITLE
Frictionless data packages produced on Windows cannot be read on Linux

### ISSUE THREAD

**Issue by as2875** [frictionlessdata/datapackage-py#272]
Take the introductory example. `population.csv` and `cities.csv` are on disk.
1. Create a package on a Windows machine
```python
package = Package()
package.infer("*.csv")
package.save("datapackage.zip")
```
2. Trying to read on a Linux machine gives an error because the resource paths in `datapackage.json` use escaped backslashes `\\`, but Linux uses slashes `/`.

@sje30, for reference.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, we're going to start Windows testing to resolve this and similar problems - https://github.com/frictionlessdata/datapackage-py/issues/266

**Comment by roll** [comment]
MERGED into https://github.com/frictionlessdata/frictionless-py/issues/388 as we're going to provide first-class support for Mac/Windows in Frictionless. 

There are some doubts that we have enough resources to replicate the effort to the `datapackage` library. But if it's really needed exactly for `datapackage` please re-open the issue :+1:
