### ISSUE TITLE
too many opened file exception caused by large multipart/chunks number 

### ISSUE THREAD

**Issue by paulgirard** [frictionlessdata/datapackage-py#276]
# Overview

I have a table-data resource with thousands of chunks.
resource.iter throw a "too many opened file" as the multipart.iter open all the streams at the same time.
Easy to solve by using a stream iterator instead.
I open a PR about this.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Fixed in #277
