### ISSUE TITLE
On Windows package creation leads to non-POSIX path string

### ISSUE THREAD

**Issue by suvayu** [frictionlessdata/datapackage-py#279]
## Overview

I am not sure if this package is supposed to work on Windows; there are no CI jobs for Windows, but the doc does not explicitly state it is unsupported either.  When I create/update a datapackage on Windows, the value of `path` for a resource is non-POSIX.  I believe this is non-conformant with the spec: https://github.com/frictionlessdata/datapackage-py/blob/cad781e8d051f2cd3d3d22bfd415cda793c694fe/datapackage/profiles/tabular-data-resource.json#L50-L92

I do not have a Windows machine myself, but I noticed because our CI failed.  So I created a separate unit test with debug statements to demonstrate the failure.  See the captured output for the unit test `test_bugreport.py::test_pathstring` ([lines 53-79](https://github.com/sentinel-energy/sentinel-archive/runs/1797244651?check_suite_focus=true#step:5:53))

(Looks like CI logs are not visible to outsiders, I'll replicate it here)

    _______________________________ test_pathstring _______________________________

    tmp_pkgdir = (WindowsPath('testing/files/mini-ex'), 
                  WindowsPath('C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_pathstring0/pkg'))

        def test_pathstring(tmp_pkgdir):
            _, dest = tmp_pkgdir
            meta = {
                "name": "foobarbaz",
                "title": "Foo Bar Baz",
                "licenses": "CC0-1.0",
                "keywords": ["foo", "bar", "baz"],
            }
            pkg = Package(meta, base_path=str(dest))
    
            fpath = "inputs/names.csv"
            assert dest / fpath
            pkg.infer(fpath)
    
            res, *_ = pkg.descriptor["resources"]
            print(res)
            assert res["path"].count("\\") > 0
    >       assert False
    E       assert False

    testing\test_bugreport.py:21: AssertionError
    ---------------------------- Captured stdout call -----------------------------
    {'path': 'inputs\\names.csv', 'profile': 'tabular-data-resource', 'name': 'names', 'format': 'csv', 'mediatype': 'text/csv', 'encoding': 'utf-8', 
     'schema': {'fields': [{'name': 'techs', 'type': 'string', 'format': 'default'}, {'name': 'names', 'type': 'string', 'format': 'default'}], 'missingValues': ['']}}

## Minimal Example

You should be able to reproduce the issue with the following recipe on Windows:

1. create a subdirectory with a CSV file in it, equivalent to the following bit of bash:

       mkdir -p mini-ex/inputs
       cat <<EOF > mini-ex/inputs/names.csv
       techs,names
       battery,Battery storage
       free_transmission,Local power transmission
       EOF

2. then run the following Python snippet:

       from datapackage import Package

       meta = {
           "name": "foobarbaz",
           "title": "Foo Bar Baz",
           "licenses": "CC0-1.0",
           "keywords": ["foo", "bar", "baz"],
       }
       pkg = Package(meta, base_path="mini-ex")

       fpath = "inputs/names.csv"
       pkg.infer(fpath)

       res, *_ = pkg.descriptor["resources"]
       print(res)
       assert res["path"].count("\\") > 0

## Further comments

I believe this is because in `resource.py`, `os.path` is used instead of something like `str(Path(..).as_posix())`
https://github.com/frictionlessdata/datapackage-py/blob/cad781e8d051f2cd3d3d22bfd415cda793c694fe/datapackage/resource.py#L830

I have not checked this against the new implementation in `frictionless`, but I hope this is addressed here as well.  That said, if the answer is use `frictionless` instead, I understand, I'll prioritise moving to the new API.

---

@roll

**Comment by roll** [comment]
Hi @suvayu,

Thanks for your feedback. This package doesn't support windows fully but our new Frictionless Framework is about to add Windows support this month - https://github.com/frictionlessdata/frictionless-py/issues/590

**Comment by suvayu** [comment]
@roll okay thanks, I'll follow the other issue, and prioritise moving to the new API.
