### ISSUE TITLE
Merge with `datapackage-storage-py`?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#51]
It's a question for next iterations but to do not forget (backlogged).

`datapackage-storage-py` is around [100 lines of code](https://github.com/okfn/datapackage-storage-py/blob/master/datapackage_storage/package.py) tightly coupled with `datapackage-py` (other 30 lines could be merged with `jsontableschema-py`).

Merging will allows `datapackage-py` users to import/export datapackages in storages supported by `jsontableschema-bigquery/sql/*-py` drivers implementing `TabularStorage` interface (only interface dependency will be introduced).

We had a discussion about it in slack so now after `registry` and `validate` merging we have to have this issue here to think in a future too.

**Comment by pwalsh** [comment]
cc @vitorbaptista 

So, some stuff we talked about in Slack. In summary, my thoughts are:

1. We add the base storage class as part of this package (likewise, the base storage for JTS goes to that package, and this depends on that).
2. We implement the storage integrations as plugins (Flask pattern is good/useful)
  * keep distinct packages like `datapackage-ckan`, `datapackage-sql`, `datapackage-bigquery`
  * Add registration pattern so that users have a much, much simplified interface via a `datapackage` object

We have to do the same on JTS. It is really important that we give JTS a nice interface, as it is very useful without data package. The data package interface should essentially wrap the JTS one with the extra things (FK support, etc,)

**Comment by roll** [comment]
> We add the base storage class as part of this package (likewise, the base storage for JTS goes to that package, and this depends on that).

Actually it's the same base storage class which supports the both worlds (jts+data=resource export/import and datapackage export/import with PK, FK etc). So having it in `jsontableschema-py` will be enough because `datapackage-py` depends upon it. Also we don't need all packages like `datapackage-sql` etc because of the same reason.

So we just need:
1. split `datapackage-storage-py` between `jsontableschema.py` (Storage API + resource.py) and `datapackage-py` (package.py)
2. add dynamic drivers loading to `jsontableschema.py` and `datapackage-py`

That's all) We don't even need to write more code (or add more repos) except simple dynamic loader like:

```
dp[].Resource:

    def export(self, driver, **params):
        try:
           module = importlib.import_module('jsontableschema_%s')
           storage = module.Storage(**params)
        except ImportError:
           raise ValueError('Driver %s is not installed' % driver).
        <here code from datapackage-storage-py package.py>
```

**Comment by pwalsh** [comment]
But we need more repos, like, to house the SQL logic, or the BigQuery logic, and coming up, Mongo, DAT, etc etc logic. Apart from that point, yes, great, we should do this. Let's wait for Vitor to chime in too before we spec out a plan of action for addressing in future (coming months).

**Comment by roll** [comment]
I meant after proposed change to support mongo we just need to write 1 repo `jsontableschema-mongo-py` and add it to `datapackage-py` as dependency - that's all. Now user could do:
```
dp.export('mongo', **mongo_connection_option)
```
So no `datapackage-mongo` repo.

**Comment by vitorbaptista** [comment]
@roll If I understood correctly, you're saying that (for example) the logic to work with mongo is encapsulated in `jsontableschema-mongo-py`, and that all DataPackage does is use it under the hood? In that case, there'll be no `datapackage-*-py`, just `jsontableschema-*-py`?

If so, your proposal sounds good to me :+1:

**Comment by roll** [comment]
@vitorbaptista Yes it is. For example you could check how it works in `datapackage-storage-py` - no special logic for bigquery or sql - just usage of unified `TabularStorage` instance.

**Comment by pwalsh** [comment]
@roll @vitorbaptista great. 

Any estimates on:

* Effort to consolidate the code libraries as described
* Effort to tidy up user API when using a storage backend (via plugin system on JTS and DP libs, or similar)

Just rough guess stuff now would be a great help.

**Comment by roll** [comment]
@pwalsh I could be 1-2 days.

**Comment by pwalsh** [comment]
Thanks @roll

**Comment by roll** [comment]
DONE
https://github.com/frictionlessdata/datapackage-py/pull/66
