### ISSUE TITLE
Test CSV dialect options

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#57]
The code merged in https://github.com/datapackages/datapackage-py/pull/56 is missing tests. As we're just calling Tabulator, we could assume it's tested and use mocks. Whatever is easier.

**Comment by vitorbaptista** [comment]
Also add tests for the exceptions thrown (for example, when `delimiter` has multiple chars). It seems that the exception thrown is always `TypeError`, which is OK, we just need to add that to the docstrings.

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/15
