### ISSUE TITLE
Only load the registry when it's needed

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#59]
For example, the registry shouldn't be loaded when a `DataPackage` is created as `datapackage.DataPackage('/path/to/datapackage.json', '/path/to/schema.json')`. The schema path is being passed explicitly, to the registry isn't used at all.

To do this, we would have to change both `Schema._load_schema` and `Schema._load_validator`. The biggest complicator is deciding if a string contains a file, a URL, or a schema ID, and load the registry or not, depending on the answer. An easier solution can be simply defaulting to an empty registry if the actual one couldn't be loaded, but then we have to make sure we at least log the exception to avoid creating some hard-to-find bugs

The reason for fixing this issue is to allow using this library even if there're problems loading the registry (e.g. the local cache file is inacessible for some reason like https://github.com/frictionlessdata/tabulator-py/issues/48).

**Comment by pwalsh** [comment]
@roll great thing to do, but not related to updating specs to v1. Please do not do until after updates related to specific v1 changes.

**Comment by roll** [comment]
CLOSED
With specs-v1 and updated library focal point of validation is `Profile` class so I don't see this issue problem is actual. Otherwise someone will raise it as a bug.
