### ISSUE TITLE
Fix tests on Windows

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#64]
Our [build on Windows](https://ci.appveyor.com/project/vitorbaptista/datapackage-py) is failing.

Most of the issues revolve around using `\r\n` as linebreak and the different paths (`C:\\foo\\bar.csv` instead of `/foo/bar.csv`), so they should be easy to fix. However, as far as I know, no one on the dev team has a Windows machine.

Fixing this issue would be a great contribution for someone with a couple hours to spare :+1:

**Comment by roll** [comment]
WONTFIX 
Windows/OSX testing will be reconsidered on the whole stack level - https://github.com/frictionlessdata/stack/issues/10
