### ISSUE TITLE
[org] Add testsuite-py repository

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#65]
Here is an idea of having comprehensive test suite against our whole stack (repo/component integration test suite). We don't have org-level issued tracker so I'm placing it here for now.

There are 2 main reasons to do it:
- Different packages integration tests don't have a proper place to store. For example - integration between datapackage and sql/bigquery/* storage drivers.
- For now our test system is kinda fragile - it works on repo-level but we don't have kinda stack `checksum` to be sure everything works as expected. Example from real live - `datapackage-py` had an api breaking change -> all integrations stop to work but we even didn't know about it. The same could happen because of `tabulator-py` change etc.

So proposed way is to have `testsuite-py` repo triggered to run very high-level tests (it could be BDD for example) on every `tabulator-py`, `datapackage-py`, `jsontableschema-py`, `jsontableschema-*-py` etc push to master (or pypi):
- datasets from https://github.com/datasets + openspending dataset etc
- dataprotocols from http://dataprotocols.org/ (protocol change also could break stack)
- wrapped into `datapackage-py` or `jsontableschema-py`
- checked with `sql/bigquery/*` integrations - import/export

So having this we'll ensure our stack is working from top-to-bottom on every underlaying packages changes.

I've started this work as a part of `datapackage-storage-py` - https://github.com/okfn/datapackage-storage-py/tree/master/examples - but now it's going to be deprecated so I need a new place for this tests. And I think place it to `datapackage-py` will be wrong because it tests data + repo integrations (not related to datapackage).

**Comment by pwalsh** [comment]
@roll ok, now I get you. An integration test suite for the core libs in the Frictionless Data ecosystem. Yes.

**Comment by pwalsh** [comment]
Also @roll about the org tracker, on OpenSpending and OpenTrials I did it like that as for many people, they experience it as "one product", and therefore it can be easier to manage the issue tracking like that (my assumption, let's see if it is correct or incorrect). But for Frictionless Data, it is modular by design, so I think we stay with the more normal case of issue tracker per repo.

**Comment by roll** [comment]
Ok. We just need some place to write (when chat is too messy for it) things about overall architecture, maintainers assignment etc project level stuff. We could do it here (because `datapackage-py` is the most high-level package) or in `testsuite-py` repo because it's about integration.

**Comment by roll** [comment]
FIXED

https://github.com/frictionlessdata/testsuite-py
