### ISSUE TITLE
Integration with Pandas

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-py#73]
This is a suggestion by @psychemedia on the old datapackage library repository. Check https://github.com/trickvi/datapackage/issues/22 for more info.

**Comment by sirex** [comment]
I'm started to work on this feature. You can find my code here: https://github.com/sirex/jsontableschema-pandas-py

I'm planing to implement this as `jsontableschema` plugin. The idea to convert data package to a `Storage` container, containing data tables converted to Pandas DataFrames. Then this container can be used like this:

```python
storage = Storage()
storage.create('table', schema)
storage.write('table', data)
storage['table']  # <-- this is pandas.DataFrame
```

Example above involves only low level code from `jsontableschema_pandas` plugin, higher level example could look like this:

```python
import datapackage
storage = datapackage.DataPackage(schema).to_pandas()
storage['table'].head()
```

The work is 80%.

**Comment by psychemedia** [comment]
In passing, I note a new binary file format for `pandas` and `R`: [*feather*](https://blog.rstudio.org/2016/03/29/feather/)

I appreciate aim of frictionless data is to support text-file / human readable CSV and provide a long term storage format, which `feather` isn't geared up for. But in the sense that *frictionless data* also provides a way of moving short lived data between different applications, *feather* is desgned for doing that with large data files.

**Comment by sirex** [comment]
Done. Here is a working example:

```python
import datapackage

descriptor = 'http://data.okfn.org/data/core/country-list/datapackage.json'
storage = datapackage.push_datapackage(descriptor, 'pandas')
storage['data___data'].head()
```

You can find full examples here:

https://gist.github.com/sirex/d65113958a062586c1d484921648057d

And the code: https://github.com/sirex/jsontableschema-pandas-py

There is only one thing, that does not work. Currently `datapackage.push_datapackage` does not return storage. Since python Pandas data frames are stored in memory, there is no way how to get them, unless storage is returned by `datapackage.push_datapackage`.

Examples above use slightly modified version of `datapackage-py`, where `storage` instance is returned by `datapackage.push_datapackage`.

Tested this on several datapackages, everything seems to work.

Also there is support for pulling existing Pandas dataframes to a datapackage.

**Comment by pwalsh** [comment]
@sirex awesome, awesome work! thank you so much for getting this rolling..

I think it is quite reasonable to return the storage object with push data package (and return, from example, a data package object with pull).

Ultimately, I think we want to implement push/pull with a more OO design ( cc @vitorbaptista @roll ), but in the meantime, I think it would be great if you want to make a PR on always returning storage with push. This would have to be some generic API that any storage backend could hook into I guess.

Lastly, I would **love** to move this repo into the `frictionlessdata` namespace here on GitHub, with you as maintainer of course. How would you feel about that? Pandas integration is really important and I think we should have it here. Of course, we can keep a copy here too.

@roll could I ask you to spend 1-2 hours in the coming days to review the Pandas integration and basically give @sirex any help needed to:

- Have the lib standardised with the general storage mechanism as you designed it
- Help with anything we need along our coding standards to prepare for a publication to pypi.

**Comment by roll** [comment]
Yes of course. We're in touch with @sirex in Gitter. He's doing great work lately :+1:

**Comment by roll** [comment]
DONE
https://github.com/frictionlessdata/jsontableschema-pandas-py
thanks to @sirex
