### ISSUE TITLE
Support datapackage-identifier spec and load data packages from all those identifiers

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/datapackage-py#76]
At the moment require explicit path to datapackage.json.

We should support all identifiers in http://dataprotocols.org/data-package-identifier/ and support loading this way e.g.

```
dp = DataPackage('.')
dp = DataPackage('./my-data-package')
dp = DataPackage('https://github.com/datasts/gdp')
```

We also need to store this info internally so we can compute path offsets for resources etc - see #75

**Comment by pwalsh** [comment]
👍

**Comment by roll** [comment]
Based on the latest direction of the development of the spec - https://github.com/frictionlessdata/specs/issues/688 - we're closing it for now, as Data Package Identifier might be deprecated (URL as the only standard location pointer instead of Datahub/Github/etc dependencies)
