### ISSUE TITLE
Add odo support?

### ISSUE THREAD

**Issue by femtotrader** [frictionlessdata/datapackage-py#77]
Hello,

maybe you should consider to add support to odo
http://odo.readthedocs.org/
so it will become possible have several outputs / inputs :
- get a Pandas DataFrame (see also https://github.com/frictionlessdata/datapackage-py/issues/73 )
- store to a database supported by SQLAlchemy
  ...

Kind regards

see https://github.com/trickvi/datapackage/issues/45

**Comment by roll** [comment]
@femtotrader 
Thanks!

To export to SQL you could use https://github.com/frictionlessdata/datapackage-py#pushpull-data-package-to-storage

**Comment by roll** [comment]
@femtotrader 
Now jsontableschema-pandas ia also available - https://github.com/frictionlessdata/jsontableschema-pandas-py 

Is this issue still actual?

**Comment by femtotrader** [comment]
Hi @roll 

@vitorbaptista @sirex and you did great work on this `datapackage-py` package.
I'm quite busy these days... so I won't be able to work on this but it will be great if you could have a look at such feature because it will became easy to output a DataPackage to several kind of destination (not only SQL databases).

Kind regards

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/implementations/issues/16

This issue seems should be resolved on higher-level than the data package library.
