### ISSUE TITLE
Cast proper types when loading resource data?

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/datapackage-py#82]
I was following the [Python quick start guide](http://frictionlessdata.io/guides/quick-start-in-python/) and playing with the [periodic table](http://frictionlessdata.io/example-datasets/periodic-table/datapackage.json) DP. 

I checked the resource metadata and the schema correctly describes `atomic number` and `atomic mass` as `integer` and `number` respectively, but when I tried to do:

```
> print [e['name'] for e in dp.resources[0].data if e['atomic number'] < 10]
[]
```

I noticed that the data has these fields as strings:

```
> print dp.resources[0].data[0]
{u'metal or nonmetal?': u'nonmetal', u'symbol': u'H', u'atomic number': u'1', u'name': u'Hydrogen', u'atomic mass': u'1.00794'}
```

Not sure about how the parsing works but would it make sense to use to information on the schema to cast the values appropriately?

**Comment by akariv** [comment]
@vitorbaptista it seems that this fix would be quite useful.

Any recommendations on implementation? I'm thinking changing `TabulatorIterator` to use the schema to cast raw resource values into actual values. This would affect all users of the library though.
Another option would be to add an `iter_cast` method (or any other name) which iterates & does the casting without changing `iter()`'s functionality.

**Comment by vitorbaptista** [comment]
@akariv I think it should, ideally, be the default behaviour. It looks a bit tricky to implement, though. Maybe wrap the iterator returned by Tabulator in another one that casts the values before yielding them? Hopefully, `jsonschema` can help us here.

If possible, it would be good to implement this for any type of resources (and not just tabular), but this might make things more difficult, so I'm happy on having it working with tabular resources and we can figure out later.

**Comment by akariv** [comment]
@vitorbaptista `TabulatorIterator` is already a wrapper in datapackage-py, so it's the ideal place to add the casting logic (with `jsontableschema-py` to actually do all the heavy lifting).
I'll send a PR soon for you to review.
