### ISSUE TITLE
Rename metadata to descriptor

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/datapackage-py#88]
We put the descriptor on the `metadata` property of a `DataPackage` to prevent clashes with other method names. I think we should rename `metadata` to `descriptor`, which is consistent with the DP terminology and less confusing IMHO.

- https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/datapackage.py#L26
- https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/datapackage.py#L66

@vitorbaptista @roll @rgrp thoughts?

**Comment by vitorbaptista** [comment]
Agreed :+1:

It used to be `descriptor`, but I changed because I thought `metadata` was more common. "Descriptor" to me, for some reason, feels like a "pointer", so it was a bit confusing. We should keep the terminology consistent, though, so we should change it to `descriptor`.

**Comment by pwalsh** [comment]
@vitorbaptista great. I'll do a PR.

**Comment by pwalsh** [comment]
PR at https://github.com/frictionlessdata/datapackage-py/pull/89

**Comment by rgrp** [comment]
@pwalsh just saying i think this is a great rename - naming is one of the 2 hardest things in coding ;-) We should do this in datapackage-js as well ...

**Comment by pwalsh** [comment]
@rgrp thanks. Yes, we'll roll it out over the js libs too. Already done so in [jsontableschema-js](https://github.com/frictionlessdata/jsontableschema-js) and will do on datapackage-js when we can turn to it.

**Comment by lexman** [comment]
cc @danfowler your project https://github.com/frictionlessdata/ex-continuous-data-integration will fail on travis once the new version of datapackakge is released. In a project derived from yours, I had to replace 3 occurences in file scripts/test_data.py
