### ISSUE TITLE
Type-casting partial dates

### ISSUE THREAD

**Issue by wfdd** [frictionlessdata/datapackage-py#91]
The README example won't parse:

```
In [8]: dp = datapackage.DataPackage('http://data.okfn.org/data/core/gdp/datapackage.json')

In [9]: dp.resources[0].data
  ...
ValueError: time data '1968' does not match format '%Y-%m-%d'
```

This is after @75dac0e.  Parsing ISO dates in Python might not be worth the trouble; `datetime.datetime` has no conception of precision, so even if you were to account for missing components... 

```
In [1]: import datetime

In [2]: datetime.datetime.strptime('1968', '%Y')
Out[2]: datetime.datetime(1968, 1, 1, 0, 0)
```

1968 is mangled into an exact date, 1/1/1968.

**Comment by roll** [comment]
MERGED
https://github.com/frictionlessdata/datapackage-py/issues/68

**Comment by wfdd** [comment]
This is an implementation, not a documentation, issue.

**Comment by roll** [comment]
@wfdd 
Data Package used is readme doesn't match version of specs supported by this library for now.

It will be updated pretty soon - https://github.com/frictionlessdata/datapackage-py/issues/131
