### ISSUE TITLE
undefined variable in _iter_from_tabulator function

### ISSUE THREAD

**Issue by ndkv** [frictionlessdata/datapackage-py#96]
The `value` variable on [line 325](https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/resource.py#L325) in `resource.py` is undefined. 

I encountered it while running the example code in the README. 

```python
import datapackage

dp = datapackage.DataPackage('http://data.okfn.org/data/core/gdp/datapackage.json')
brazil_gdp = [{'Year': int(row['Year']), 'Value': float(row['Value'])}
              for row in dp.resources[0].data if row['Country Code'] == 'BRA']
```

This throws a `NameError` for `value` in the `_iter_from_tabulator` function. Note: this error is not caught by Travis. 

I'm not familiar with `jsontableschema` and can't quickly see how to fix this. Any help is greatly appreciated as I'd like to address #63.

**Comment by ndkv** [comment]
In addition, the example code will always fail because the dates in the referenced data package are formatted as `yyyy` which cannot be cast by [jsontableschema.types.date.DateType](https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/types/date.py) as there is no `cast_yyyy()` function.

Adding one is easy but I'm not sure if that's the desired solution.

**Comment by danfowler** [comment]
@ndkv Thanks for flagging!  As of the current spec (http://specs.frictionlessdata.io/json-table-schema/#date), that `datapackage.json` should actually use this for the date:

```
"pattern": "fmt:%Y"
```

However, this is not particularly well liked and is currently under discussion for replacement: https://github.com/frictionlessdata/specs/issues/260 (your thoughts welcome!)

We should update the gdp dataset to at least match the current spec, but it *might* break the old OpenSpending (https://openspending.org/) which relies on this formatting and might be pulling in that dataset.

**Comment by scls19fr** [comment]
`value` is not defined but used here https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/resource.py#L325

**Comment by ndkv** [comment]
@danfowler Right, thanks for explaining the issue. I have to agree that `fmt:%Y` doesn't _feel_ right.
